blog/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.blog, name="blog"),
    path('posts/<int:post_id>/post_detail', views.post_detail, name="post_detail"),
    path('blog_posts', views.blog_posts, name="blog_posts"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")), #mudar para "home.urls"
    path('livros', include("livros.urls")),
    path('blog', include("blog.urls")), #mudar para "blog.urls"
    path('login', include("login.urls")),
    path('contas', include("contas.urls")),
    path('quiz', include("quiz.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "home.views.handler404"
handler500 = "home.views.handler500"

quiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.quiz, name="quiz"),
path('quiz/resposta/', views.resposta, name='resposta'),
]

quiz/models.py
from django.db import models

# Create your models here.

class Pergunta(models.Model):
    enunciado = models.TextField(max_length=300, null=False, blank=False, default='')
    figura = models.ImageField(null=False, blank=False, default='')

    def __str__ (self):
        return self.enunciado

class Alternativas(models.Model):
    texto = models.TextField(max_length=300, null=False, blank=False, default='')
    correta = models.BooleanField(default=False, null=True, blank=True)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)

    def __str__(self):
        return self.texto

quiz/views.py
from django.http import HttpResponse
from django.shortcuts import render

from quiz.models import Pergunta


# Create your views here.

#### FUNÇÃO ACESSA AS PERGUNTAS DO QUIZ DE FORMA ALEATÓRIA ####
def quiz(request):
    pergunta = Pergunta.objects.order_by("?").first()
    context = {
        'pergunta': pergunta
    }
    return render(request, 'quiz/quiz.html', context)


#### FUNÇÃO QUE RETORNA O FEEDBACK DA RESPOSTA DADA PELO USUÁRIO ####
def resposta(request):

    resposta = request.POST.get('resposta')

    if resposta == 'True':
        return HttpResponse("<p style='color:green'> Resposta Correta! </p>")
    elif resposta == 'False':
        return HttpResponse("<p style='color:red'> Resposta Incorreta. </p>")
    else:
        return HttpResponse("<p style='color:orange'> Selecione uma alternativa. </p>")

quiz/templates/quiz/quiz.html
{% load static %}
<div class="card vh-75 vw-100">

    <!-- Se houver imagem vinculada a pergunta, mostrar imagem correspondente -->
    {% if pergunta.figura %}

    <img src="{{ pergunta.figura.url}}"
         class="card-img-top"
         alt="texto-pergunta">

    <!-- Caso contrário, mostrar imagem padrão -->
    {% else %}

    <img src="{% static 'blog/default.jpg' %}"
         class="card-img-top"
         alt="texto-pergunta">

    {% endif %}

    <p class="mt-1 p-3 fs-5"> {{ pergunta.enunciado }} </p>
    <form method="POST" action="{% url 'resposta' %}">
        {% csrf_token %}
        <div class="card-body p-2">

            <div class="form-check">

                <!-- Lista de alternativas -->
                <ul class="list-group list-group-flush">
                    {% for alternativa in pergunta.alternativas_set.all %}
                    <div class="list-group-item">
                        <input class="form-check-input"
                               type="radio"
                               name="resposta"
                               id="id_{{ alternativa.id }}"
                               value="{{ alternativa.correta }}">
                        <label class="form-check-label" for="id_{{ alternativa.id }}">
                            {{ alternativa.texto }}
                        </label>
                    </div>
                    {% endfor %}
                </ul>

                <!-- Botão de responder. Dependendo da resposta, o htmx irá retornar uma mensagem -->
                <button hx-post="{% url 'resposta' %}"
                        hx-target="#msg_feedback"
                        hx-trigger="click"
                        class="btn mt-2 d-grid col-12"
                        style="background-color: #8B4513; color: #f5f5dc;"> Responder </button>

            </div>
        </div>
    </form>

    <!-- Feedback conforme a resposta enviada -->
    <div class="card-footer bg-white border-0">
        <div class="text fs-5 fw-bold">
            <div class="text-center" id="msg_feedback"></div>
        </div>
    </div>

</div>