blog/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.blog, name="blog"),
    path('posts/<int:post_id>/post_detail', views.post_detail, name="post_detail"),
    path('blog_posts', views.blog_posts, name="blog_posts"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")), #mudar para "home.urls"
    path('livros', include("livros.urls")),
    path('blog', include("blog.urls")), #mudar para "blog.urls"
    path('login', include("login.urls")),
    path('contas', include("contas.urls")),
    path('quiz', include("quiz.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "home.views.handler404"
handler500 = "home.views.handler500"

blog/models.py
from ckeditor.fields import RichTextField
from django.db import models
from datetime import datetime
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField

from contas.models import Perfil


# Create your models here.

class Post(models.Model):
    autor = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=255)
    subtitulo = models.CharField(max_length=255)
    resumo = RichTextField(null=True, blank=True)
    conteudo = RichTextUploadingField(null=True, blank=True)
    imagem_post = models.ImageField(null=True, blank=True, upload_to='static/blog/')
    data_publicacao = models.DateTimeField(timezone.now())
    tempo_leitura = models.CharField(max_length=2, default=30)

    def __str__(self):
        return self.titulo

class Tag(models.Model):
    nome = models.CharField(max_length=50)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return self.nome


class Assunto(models.Model):
    nome = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return self.nome

blog/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from .models import Post


# Create your views here.

#### FUNÇÃO PARA CONSULTAR O BANCO DE DADOS DE ACORDO COM AS ÚLTIMAS INSERÇÕES ####
def blog(request):
    posts = Post.objects.order_by('-data_publicacao')[:5]

    context = {
        'posts': posts
    }

    return render(request, 'blog/blog.html', context)

#### FUNÇÃO PARA CONSULTAR O BANCO DE DADOS DE ACORDO COM O ID DOS POSTS ####
def post_detail(request, post_id):
    post = Post.objects.get(pk=post_id)

    context = {
        'post': post
    }

    return render(request, 'blog/post_detail.html', context)

#### FUNÇÃO PARA CONSULTAR O BANCO DE DADOS DE ACORDO COM AS ÚLTIMAS INSERÇÕES ####
def blog_posts(request):
    posts = Post.objects.order_by('-data_publicacao')[:4]

    context = {
        'posts': posts
    }

    return render(request, 'blog/blog_posts.html', context)

blog/templates/blog/blog.html
{% extends "base.html" %}
{% load static %}
{% block title %} Blog {% endblock %}

{% block navbar %} {% include 'fragments/navbar.html' %} {% endblock %}

{% block content %}
<div class="col-xl-8">
    <div class="row">
        <div class="col-lg-8 d-flex">

            <!-- Post principal da página -->
            <div class="card vh-75 vw-100">
                <a href="{% url 'post_detail' posts.0.id %}">
                    <img src="{{ posts.0.imagem_post.url }}" class="card-img-top" alt="Imagem do card">
                </a>
                <div class="card-body pb-4">
                    <a href="{% url 'post_detail' posts.0.id %}" class="text-decoration-none text-dark">
                        <h3 class="card-title" style="color: #8B4513;"><strong>{{ posts.0.titulo }}</strong></h3>
                    </a>
                    <p class="card-text">{{ posts.0.resumo|safe }}</p>
                    <p class="card-text">
                        <small class="text-muted">{{ posts.0.data_publicacao }}</small>
                    </p>
                </div>
            </div>

        </div>

            <!-- Quiz -->
        <div class="col-lg-4 d-none d-lg-flex" hx-get="quiz" hx-trigger="load">
            {% include 'quiz/quiz.html' %}
        </div>

    </div>
    <hr class="my-4">

    <!-- Faixa com o escrito "Posts recentes" -->
    <div class="container py-2 d-flex justify-content-center rounded" style="background-color: #8B4513;">
        <h1 style="color: #f5f5dc;">Posts recentes</h1>
    </div>

    <hr class="my-4">

    <!-- For que roda os 4 últimos posts postados -->
    <div class="row row-cols-1 row-cols-md-2 g-2">
        {% for post in posts|slice:"0:4" %}
        <div class="col d-flex">
            <div class="card vh-75 vw-100">
                <a href="{% url 'post_detail' post.id %}">
                    <img src="{{ post.imagem_post.url }}"
                         class="card-img-top img-250"
                         alt="Imagem referente ao livro">
                </a>
                <div class="card-body pb-3">
                    <a href="{% url 'post_detail' post.id %}" class="text-decoration-none text-dark">
                        <h4 class="card-title" style="color: #8B4513;"><strong>{{ post.subtitulo }}</strong></h4>
                    </a>
                    <p class="card-text">{{ post.resumo|slice:":230"|safe }}...</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Link para redirecionar o usuário a página que contém todos os posts -->
    <div class="my-2 text-end">
        <a href="{% url 'blog_posts' %}" class="fw-bold" style="color: #8B0000;">Mais posts...</a>
    </div>

</div>
    {% endblock %}

    {% block footer %} {% include 'fragments/footer.html' %} {% endblock %}

blog/templates/blog/blog_posts.html
{% extends "base.html" %}
{% load static %}
{% block title %} Posts do Blog {% endblock %}

{% block navbar %} {% include 'fragments/navbar.html' %} {% endblock %}

{% block content %}

            <!-- For que mostra todos os posts postados -->
            <div class="col-xl-7">
                {% for post in posts %}
                    <div class="card mx-5 px-5 py-2">
                        <a href="{% url 'post_detail' post.id %}">
                            <img src="{{ post.imagem_post.url }}" class="card-img-top" alt="Imagem do card">
                        </a>
                        <div class="card-body pb-4">
                            <a href="{% url 'post_detail' post.id %}" class="text-decoration-none text-dark">
                                <h3 class="card-title" style="color: #8B4513;"><strong>{{ post.subtitulo }}</strong></h3>
                            </a>
                            <p class="card-text">{{ post.resumo|safe }}</p>
                            <p class="card-text">
                                <small class="text-muted">{{ post.data_publicacao }}</small>
                            </p>
                        </div>
                    </div>

                <div class="my-3"></div>
                {% endfor %}
            </div>

{% endblock %}

{% block footer %} {% include 'fragments/footer.html' %} {% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %} Post {% endblock %}

{% block navbar %} {% include 'fragments/navbar.html' %} {% endblock %}

{% block content %}

<div class="col-xl-8">

    <hr class="my-4" style="color: #8B4513;">

    <div class="container-fluid px-0">
        <div class="flex-row d-flex my-2">
            <h2 style="color: #8B4513;"> {{ post.titulo }}</h2>

            <!-- Contém todos os ícones de redes sociais e compartilhamento -->
            <span class=" d-flex justify-content-center align-items-center ms-5">
                            <a href="#" class="text-decoration-none text-dark">
                                <span class="ms-3"
                                      data-bs-toggle="tooltip"
                                      data-bs-placement="top"
                                      title="Compartilhe no Instagram!">

                                <i class="fa-brands fa-instagram fa-2xl" style="color: #8B4513;"></i>

                            </span>
                            </a>
                            <a href="#" class="text-decoration-none text-dark">
                                <span class="ms-3"
                                      data-bs-toggle="tooltip"
                                      data-bs-placement="top"
                                      title="Compartilhe no Facebook!">
                                <i class="fa-brands fa-facebook fa-2xl" style="color: #8B4513;"></i>

                            </span>
                            </a>
                            <a href="#" class="text-decoration-none text-dark">
                                <span class="ms-3"
                                      data-bs-toggle="tooltip"
                                      data-bs-placement="top"
                                      title="Compartilhe no WhatsApp!">

                                <i class="fa-brands fa-whatsapp fa-2xl" style="color: #8B4513;"></i>

                            </span>
                            </a>
                            <a href="#" class="text-decoration-none text-dark">
                                <span class="ms-3"
                                      data-bs-toggle="tooltip"
                                      data-bs-placement="top"
                                      title="Compartilhe no Twitter!">

                                <i class="fa-brands fa-twitter fa-2xl" style="color: #8B4513;"></i>

                            </span>
                            </a>
                            <a href="#" class="text-decoration-none text-dark">
                                <span class="ms-3"
                                      data-bs-toggle="tooltip"
                                      data-bs-placement="top"
                                      title="Copie o link!">

                                <i class="fa-solid fa-link fa-2xl" style="color: #8B4513;"></i>

                            </span>
                            </a>
            </span>

        </div>
    </div>

    <!-- Cabeçalho do post -->
    <div class="row">
        <div class="col-12">
            <div class="d-flex flex-row align-items-center">
                <div class="rounded-circle border d-flex justify-content-center
                            align-items-center bg-info avatar">
                    <img src="{{ post.autor.foto.url }}"
                         style="height:85px; width:85px"
                         class="rounded-circle">
                </div>

                <p class="mb-0">
                                <span class="text-muted justify-content-center">
                                    <span class="mx-2 h5" style="color: #8B4513;">
                                        {{ post.autor }}
                                    </span>

                                    <span>
                                        <i class="fa-solid fa-clock" style="color: #8B4513;"></i>
                                        <span style="color: #8B4513;">
                                            {{ post.tempo_leitura }}Min
                                        </span>
                                    </span>

                                    <br>

                                    <span class="ms-2 me-1"><i class="fa-solid fa-tags" style="color: #8B4513;"></i></span>
                                    {% for tag in post.tag_set.all %}
                                    <span style="color: #8B4513;">
                                        <a href="#" class="text-decoration-none" style="color: #8B4513;">#{{ tag.nome }}</a>
                                    </span>
                                    {% endfor %}

                                    <br>

                                    <span class="mx-2" style="color: #8B4513;">
                                        {{ post.subtitulo }}
                                    </span>
                                </span>
                </p>
            </div>
        </div>
    </div>

    <hr class="my-4" style="color: #8B4513;">

    <!-- Conteúdo do post -->
    <article class="fs-5" style="font-family: 'Times New Roman', Times, serif;">
        {{ post.conteudo|safe }}
    </article>

    <hr class="my-4" style="color: #8B4513;">

</div>


{% endblock %}

{% block footer %} {% include 'fragments/footer.html' %} {% endblock %}