blog/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.blog, name="blog"),
    path('posts/<int:post_id>/post_detail', views.post_detail, name="post_detail"),
    path('blog_posts', views.blog_posts, name="blog_posts"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")), #mudar para "home.urls"
    path('livros', include("livros.urls")),
    path('blog', include("blog.urls")), #mudar para "blog.urls"
    path('login', include("login.urls")),
    path('contas', include("contas.urls")),
    path('quiz', include("quiz.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "home.views.handler404"
handler500 = "home.views.handler500"

livros/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.livros, name="livros"),
]

home/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.utils import timezone

# Create your models here.
class Universidade(models.Model):
    nome = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.nome

class Categoria(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    descricao = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nome

class Livro(models.Model):
    autor = models.CharField(max_length=255)
    titulo = models.CharField(max_length=255)
    sinopse = RichTextField(null=True, blank=True)
    ano_publicacao = models.PositiveIntegerField()
    editora = models.CharField(max_length=200)
    capa = models.ImageField(null=True, blank=True, upload_to='static/blog/')
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True, related_name='livros')
    link_spotify = models.URLField(null=True, blank=True)
    link_amazon = models.URLField(null=True, blank=True)
    link_pdf = models.URLField(null=True, blank=True)
    resenha = RichTextField(null=True, blank=True)
    paginas = models.CharField(max_length=5, default=30)

    def __str__(self):
        return self.titulo

class Vestibular(models.Model):
    nome = models.CharField(max_length=200)
    universidade = models.ForeignKey(Universidade, on_delete=models.CASCADE, related_name='vestibulares')
    data = models.DateField()
    livros = models.ManyToManyField(Livro)

    class Meta:
        unique_together = ('nome', 'universidade')

    def __str__(self):
        return self.nome

livros/models.py
from django.db import models
from home.models import Livro

# Create your models here.

livros/views.py
from django.shortcuts import render
from .models import Livro
# Create your views here.

#### FUNÇÃO PARA ACESSAR A ENTIDADE LIVRO DE ACORDO COM O ID ####
def livros(request):
    livros = Livro.objects.order_by('-id')

    context = {
        'livros': livros,
    }

    return render(request, 'livros/livros.html', context)

livros/templates/livros/livros.html
{% extends "base.html" %}
{% load static %}
{% block title %} Livros {% endblock %}

{% block navbar %} {% include 'fragments/navbar.html' %} {% endblock %}

{% block content %}
<div class="col-xl-8">
{% for livro in livros %}
    <div class="card mb-3" style="width: 100%; height:370px;">
        <div class="row g-0">

            <!-- Imagem de capa do livro -->
            <div class="col-md-4" style="width: 223px; height:370px;">
                <a href="{% url 'book_detail' livro.id %}" class="text-decoration-none text-dark">
                    <img src="{{ livro.capa.url }}" class="img-fluid rounded-start" alt="Capa do livro">
                </a>
            </div>

            <div class="col-md-8">

                <!-- Informações básicas sobre o livro -->
                <div class="card-body ps-4">
                    <a href="{% url 'book_detail' livro.id %}" class="text-decoration-none text-dark">
                        <h3 class="card-title" style="color: #8B4513;"><strong>{{ livro.titulo }}</strong></h3>
                    </a>
                    <p class="card-text">{{ livro.sinopse|slice:":400"|safe }}...</p>
                    <p class="card-text">
                        <small class="text-body-secondary" style="font-style: italic;">{{ livro.autor }}</small>
                    </p>
                    {% for vestibular in livro.vestibular_set.all %}
                    <p class="card-text"><strong>{{ vestibular.nome }}</strong></p>
                    {% endfor %}
                </div>

                <!-- Div que mostra opções para o vestibulando acessar o livro -->
                <div class="row ps-4">
                    <div class="col-12">
                        <div class="d-flex">
                            <div class="span ms-0 ps-0 btn">

                                <a href="{{ livro.link_pdf }}" class="text-decoration-none text-dark"><i
                                        class="me-2 fa-solid fa-file-pdf fa-2xl" style="color: #8B4513;"></i></a>Acessar {{ livro.titulo }}

                            </div>
                            <div class="span ms-3 btn">
                                <a href="{{ livro.link_amazon }}" class="text-decoration-none text-dark"><i
                                        class="me-2 fa-brands fa-amazon fa-2xl" style="color: #8B4513;"></i></a>Comprar {{ livro.titulo }}

                            </div>
                            <div class="span ms-3 btn">

                                <a href="{{ livro.link_spotify }}" class="text-decoration-none text-dark"><i
                                        class="me-2 fa-brands fa-spotify fa-2xl" style="color: #8B4513;"></i></a>Ouvir {{ livro.titulo }}

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block footer %} {% include 'fragments/footer.html' %} {% endblock %}